set serveroutput on
BEGIN 
FIRST_PACKAGE.LIST_STORE;
FIRST_PACKAGE.ADD_STORE(12,'AAAA','7856435634');
FIRST_PACKAGE.LIST_STORE;
FIRST_PACKAGE.DEL_STORE(12);
FIRST_PACKAGE.ADD_SALE(1,'SALE',345);
END; 
/  